services:
  kindness-box-bot:
    container_name: kindness-box-bot
    build:
      context: .
    environment:
      BOT_ACCESS_TOKEN_FILE: /run/secrets/bot/access_token
      BOT_GROUP_ID_FILE: /run/secrets/bot/group_id

      MONGO_HOST: kindness-box-mongo
      MONGO_PORT: 27017
      MONGO_USERNAME_FILE: /run/secrets/mongo/username
      MONGO_PASSWORD_FILE: /run/secrets/mongo/password
      MONGO_DATABASE: kindness-box

    depends_on:
      - kindness-box-mongo
    secrets:
      - bot
      - mongo

  kindness-box-mongo:
    container_name: kindness-box-mongo
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo/username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo/password

    secrets:
      - mongo
    volumes:
      - "./.mongo/:/data/db"
    ports:
      - "27017:27017"

secrets:
  mongo:
    file: ./.secrets/mongo
  bot:
    file: ./.secrets/bot
